### PR TITLE
New Lunchtime Guac Recipe

### PR DESCRIPTION
**Pull request by chwong11**
## 🎯 Objective
Please confirm which suggested ingredients you would like to have! Please leave some ingredients for others to confirm/commit

## 🛠️ Changes made
Added new recipe with suggested ingredients for you to pick and choose! 

## 👥 Who needs to review this Pull Request? 
@kongtianshou 
@tfantis
@johnaeastman 
@LSallersonberk

### CODE REVIEW

**Review by johnaeastman — APPROVED** [review]
Guac recipe looks delicious — can't wait to try it! Approving merging these changes 😊

**Comment by chwong11** [comment]
> Guac recipe looks delicious — can't wait to try it! Approving merging these changes 😊

Thanks John, can you make an additional edit by choosing one of the suggested ingredients and commit the change? We actually all need to commit an edit and contribute to each of the recipes!

**Review by kongtianshou — COMMENTED** [review]
What a healthy lunch!

**Review by kongtianshou — APPROVED** [review]
looks good

**Comment by johnaeastman** [comment]
> > Guac recipe looks delicious — can't wait to try it! Approving merging these changes 😊
> 
> Thanks John, can you make an additional edit by choosing one of the suggested ingredients and commit the change? We actually all need to commit an edit and contribute to each of the recipes!

Yes — done!

**Review by kongtianshou — APPROVED** [review]
looking great!

**Pull request merged**
